captainVersion: 4
services:
  $$cap_appname-mysql:
    image: mysql:8.0.36
    volumes:
      - $$cap_appname-mysql-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $$cap_mysql_root_password
      MYSQL_DATABASE: $$cap_mysql_database
      MYSQL_USER: $$cap_mysql_user
      MYSQL_PASSWORD: $$cap_mysql_password
    caproverExtra:
      notExposeAsWebApp: true

  $$cap_appname-redis:
    image: redis:latest
    volumes:
      - $$cap_appname-redis-data:/data
    restart: unless-stopped
    caproverExtra:
      notExposeAsWebApp: true

  $$cap_appname-api:
    image: ghcr.io/parcelvoy/api:$$cap_parcelvoy_api_version
    restart: unless-stopped
    depends_on:
      - $$cap_appname-mysql
      - $$cap_appname-redis
    environment:
      NODE_ENV: $$cap_node_env
      BASE_URL: https://$$cap_appname.$$cap_root_domain
      RUNNER: api
      APP_SECRET: $$cap_gen_random_hex(32)
      PORT: 3001
      DB_CLIENT: mysql
      DB_HOST: srv-captain--$$cap_appname-mysql
      DB_USERNAME: $$cap_mysql_user
      DB_PASSWORD: $$cap_mysql_password
      DB_PORT: 3306
      DB_DATABASE: $$cap_mysql_database
      QUEUE_DRIVER: redis
      REDIS_HOST: srv-captain--$$cap_appname-redis
      REDIS_PORT: 6379
      AUTH_OPENID_ISSUER_URL: ${AUTH_OPENID_ISSUER_URL}
      AUTH_OPENID_CLIENT_ID: ${AUTH_OPENID_CLIENT_ID}
      AUTH_OPENID_CLIENT_SECRET: ${AUTH_OPENID_CLIENT_SECRET}
      AUTH_OPENID_REDIRECT_URI: ${AUTH_OPENID_REDIRECT_URI}
      AUTH_OPENID_DOMAIN_WHITELIST: ${AUTH_OPENID_DOMAIN_WHITELIST}
      AUTH_OPENID_RESPONSE_TYPES: ${AUTH_OPENID_RESPONSE_TYPES}
      AUTH_OPENID_NAME: ${AUTH_OPENID_NAME}
    volumes:
      - $$cap_appname-uploads:/usr/src/app/public/uploads
    caproverExtra:
      containerHttpPort: 3001

  $$cap_appname-worker:
    image: ghcr.io/parcelvoy/api:$$cap_parcelvoy_api_version
    restart: unless-stopped
    depends_on:
      - $$cap_appname-mysql
      - $$cap_appname-redis
      - $$cap_appname-api
    environment:
      NODE_ENV: $$cap_node_env
      BASE_URL: https://$$cap_appname.$$cap_root_domain
      RUNNER: worker
      APP_SECRET: $$cap_gen_random_hex(32)
      DB_CLIENT: mysql
      DB_HOST: srv-captain--$$cap_appname-mysql
      DB_USERNAME: $$cap_mysql_user
      DB_PASSWORD: $$cap_mysql_password
      DB_PORT: 3306
      DB_DATABASE: $$cap_mysql_database
      REDIS_HOST: srv-captain--$$cap_appname-redis
      REDIS_PORT: 6379
    caproverExtra:
      notExposeAsWebApp: true

  $$cap_appname-ui:
    image: ghcr.io/parcelvoy/ui:$$cap_parcelvoy_ui_version
    restart: unless-stopped
    depends_on:
      - $$cap_appname-api
    environment:
      API_BASE_URL: https://$$cap_appname-api.$$cap_root_domain
    caproverExtra:
      containerHttpPort: 3000

caproverOneClickApp:
  variables:
    - id: $$cap_mysql_root_password
      label: MySQL Root Password
      description: Password for MySQL root user
      defaultValue: $$cap_gen_random_hex(16)
    
    - id: $$cap_mysql_database
      label: MySQL Database Name
      description: Name of the MySQL database
      defaultValue: parcelvoy
    
    - id: $$cap_mysql_user
      label: MySQL User
      description: Username for MySQL database
      defaultValue: parcelvoy
    
    - id: $$cap_mysql_password
      label: MySQL Password
      description: Password for MySQL user
      defaultValue: $$cap_gen_random_hex(16)
    
    - id: $$cap_node_env
      label: Node Environment
      description: Environment for Node.js application
      defaultValue: production
    
    - id: $$cap_parcelvoy_api_version
      label: Parcelvoy API Version
      description: Version of Parcelvoy API image to deploy
      defaultValue: latest
    
    - id: $$cap_parcelvoy_ui_version
      label: Parcelvoy UI Version
      description: Version of Parcelvoy UI image to deploy
      defaultValue: latest

  instructions:
    start: Parcelvoy is an open-source marketing automation platform
    end: Parcelvoy has been successfully deployed. Access it at https://$$cap_appname.$$cap_root_domain

  displayName: Parcelvoy
  description: Open-source marketing automation platform
  isOfficial: false