#need to check with replice, otherwise it works within localhost
---
captainVersion: 4

services:
  $$cap_appname:
    restart: 'always'
    image: $$cap_service_image:$$cap_service_tag
    command: 'start-from-init --masterkey "$$cap_secret_key" --tlsMode disabled'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: $$cap_db_host
      ZITADEL_DATABASE_POSTGRES_PORT: $$cap_db_port
      ZITADEL_DATABASE_POSTGRES_DATABASE: $$cap_db_name
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: $$cap_db_usr_name
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: $$cap_db_usr_psw
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: $$cap_db_usr_ssl
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: $$cap_db_adm_name
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: $$cap_db_adm_psw
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: $$cap_db_adm_ssl
      ZITADEL_EXTERNALSECURE: true
      ZITADEL_EXTERNALDOMAIN: $$cap_appname.$$cap_root_domain
      ZITADEL_EXTERNALPORT: 443
    caproverExtra:
      containerHttpPort: '8080'
      websocketSupport: 'true'

caproverOneClickApp:
    displayName: Zitadel - No DB (by alex-gph1)
    description: Identity infrastructure, simplified for you
    isOfficial: true
    documentation: https://zitadel.com/docs/guides/overview
    instructions:
        start: |-
            Postgres should be already installed on your system.
            The admin user is only needed for the installation step but can also be avoided by preparing the necessary requirements:
                - the zitadel user
                - the zitadel database
                - granting required permissions to the zitadel user
            
                CREATE ROLE zitadel LOGIN;
                CREATE DATABASE zitadel;
                GRANT CONNECT, CREATE ON DATABASE zitadel TO zitadel;

                !Don't forget to adjust pg_hba.conf and set a password for the zitadel user.

        end: >-
            Zitadel has been successfully deployed! Access it at `http://$$cap_appname.$$cap_root_domain`.
            

    variables:
        - id: $$cap_service_image
          label: Docker Image
          defaultValue: 'ghcr.io/zitadel/zitadel'
          validRegex: /.{1,}/

        - id: $$cap_service_tag
          label: Docker Tag
          description: Set the tag to use for the app image. View the available tags here https://github.com/zitadel/zitadel/releases
          defaultValue: 'v2.61.0'
          validRegex: /.{1,}/

        - id: $$cap_secret_key
          label: Zitadel Master Key
          description: The masterkey is used to AES256-encrypt other generated encryption keys. It must be 32 bytes. 
          defaultValue: $$cap_gen_random_hex(32)
          validRegex: /.{32}/

        - id: $$cap_db_host
          label: Database Host
          defaultValue: 'postgres'
          validRegex: /.{1,}/

        - id: $$cap_db_port
          label: Database Port
          defaultValue: '5432'
          validRegex: /\d{1,}/

        - id: $$cap_db_name
          label: Database Name
          defaultValue: 'zitadel'
          validRegex: /.{1,}/

        - id: $$cap_db_usr_name
          label: Database User Name
          defaultValue: 'zitadel'
          validRegex: /.{1,}/

        - id: $$cap_db_usr_psw
          label: Database User Password
          defaultValue: $$cap_gen_random_hex(24)
          validRegex: /.{16,}/

        - id: $$cap_db_usr_ssl
          label: Database User SSL Mode
          defaultValue: disable

        - id: $$cap_db_adm_name
          label: Database Admin Name
          defaultValue: 'root'

        - id: $$cap_db_adm_psw
          label: Database Admin Password
          defaultValue: 

        - id: $$cap_db_adm_ssl
          label: Database Admin SSL Mode
          defaultValue: disable