version: '3.9'
services:
  fleet: 
    image: fleetdm/fleet
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    healthcheck:
      test: "curl -f http://127.0.0.1/healthz"
    environment:
      FLEET_SERVER_TLS=false
      FLEET_SERVER_ADDRESS=0.0.0.0:8412
      FLEET_MYSQL_ADDRESS=mysql:3306
      FLEET_MYSQL_DATABASE=fleet
      FLEET_MYSQL_USERNAME=fleet
      FLEET_MYSQL_PASSWORD=insecure
      FLEET_REDIS_ADDRESS=redis:6379
      FLEET_REDIS_PASSWORD=redis_password
      FLEET_REDIS_CONNECT_RETRY_ATTEMPTS: 3
      FLEET_WEBHOOK_SETTINGS_INTERVAL="1M"
      FLEET_OSQUERY_LABEL_UPDATE_INTERVAL=1m
      FLEET_OSQUERY_POLICY_UPDATE_INTERVAL="2m"
      FLEET_OSQUERY_ENABLE_ASYNC_HOST_PROCESSING: true
      FLEET_PACKAGING_GLOBAL_ENROLL_SECRET=totallysecuresecret
     # FLEET_VULNERABILITIES_CURRENT_INSTANCE_CHECKS=yes
     # FLEET_VULNERABILITIES_DATABASES_PATH=/vulndb
     # FLEET_VULNERABILITIES_PERIODICITY=5m