name: Validate One Click Apps

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run validate && pnpm run format
